#
# Metadata
#

name=""
id=""
version="1.0.0"
author="Muhammad Alan Andika"

description=""

#
# Colors
#

accent="#89b4fa"
accent_bg="#45475a"

bg="rgba(24,24,37,0.92)"
fg="#cdd6f4"
text="#cdd6f4"

active_text="#11111b"

#
# Assets
#

preview="assets/preview/preview.png"
wallpaper="assets/wallpapers/default.jpg"

#
# Components
#

waybar="waybar"
hypr="hypr"
wofi="wofi"

#
# Optional Components
#

kitty="kitty"
gtk="gtk"
icons="icons"
cursor="cursor"
swaync="swaync"
