#
# Metadata
#

name="Pixel"
id="pixel"
version="1.0.0"
author="Muhammad Alan Andika"

description="Pixel inspired theme"

#
# Colors
#

accent="#89b4fa"
accent_bg="#45475a"

bg="rgba(24,24,37,0.92)"
fg="#cdd6f4"
text="#cdd6f4"

active_text="#11111b"

#
# Assets
#

preview="assets/preview/preview.png"
wallpaper="assets/wallpapers/pixel_art.jpg"

#
# Components
#

waybar="waybar"
hypr="hypr"
wofi="wofi"
swaync="swaync"

#
# Optional Components
#

kitty="kitty"
gtk="gtk"
icons="icons"
cursor="cursor"
swaync="swaync"

#
# Design
#

opacity="0.85"
radius="18"
blur="low"
animation="fast"
