name="Mountain"

id="mountain"

version="1.0.0"

author=""

description=""

wallpaper_type="image"
wallpaper="assets/wallpapers/example.jpg"

preview="assets/preview/preview.png"

waybar="waybar/style.css"

hyprlock="hypr/hyprlock.conf"

accent="#89b4fa"
accent_bg="rgba(137,180,250,0.25)"

bg="rgba(20,20,20,0.72)"
fg="#ffffff"
text="#cdd6f4"
active_text="#11111b"

requires="hyprpaper,waybar,hyprlock"
