#
# Metadata
#

name="Mountain"
id="mountain"
version="1.0.0"
author="Muhammad Alan Andika"

description="Mountain inspired theme"

#
# Colors
#

accent="#7aae7f"
accent_bg="rgba(122,174,127,0.25)"

bg="rgba(18,24,20,0.30)"
fg="#d7e8d7"
text="#d7e8d7"

active_text="#111111"

#
# Assets
#

preview="assets/preview/preview.png"
wallpaper="assets/wallpapers/biru.jpg"

#
# Components
#

waybar="waybar"
hypr="hypr"
wofi="wofi"

#
# Optional Components
#

kitty="kitty"
gtk="gtk"
icons="icons"
cursor="cursor"
swaync="swaync"

#
# Design
#

opacity="0.40"
radius="28"
blur="high"
animation="smooth"
