name="Mountain"

id="mountain"

version="1.0.0"

author=""

description=""

wallpaper_type="image"
wallpaper="assets/wallpapers/biru.jpg"

preview="assets/preview/preview.png"

waybar="waybar/style.css"

hyprlock="hypr/hyprlock.conf"
accent="#7AAE7F"
accent_bg="rgba(122,174,127,0.25)"

bg="rgba(18,24,20,0.72)"
fg="#ECEEEB"
text="#C7D1C8"
active_text="#182218"
requires="hyprpaper,waybar,hyprlock"
